# GitHub Copilot Network Configuration
# This file configures network access for GitHub Copilot coding agent

# Required endpoints for GitHub Copilot
allowed_hosts:
  - github.com
  - api.github.com
  - api.githubcopilot.com
  - *.githubusercontent.com
  - objects.githubusercontent.com
  - codeload.github.com
  
# Additional endpoints that may be needed
additional_hosts:
  - registry.npmjs.org
  - pypi.org
  - archive.ubuntu.com
  - security.ubuntu.com
  - packages.microsoft.com
  - checkpoint.prisma.io
  
# Network timeout settings
timeouts:
  connection_timeout: 30000  # 30 seconds
  read_timeout: 60000        # 60 seconds
  
# Retry configuration
retry:
  max_attempts: 5
  backoff_multiplier: 2