name: Build Windows Installer

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the build (e.g., 1.0.0)'
        required: false
        default: '1.0.0'

jobs:
  build-windows:
    name: Build Windows .exe Installer
    runs-on: windows-latest
    
    defaults:
      run:
        working-directory: ./Financials Automation
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build web application
        run: pnpm run build
      
      - name: Build Electron scripts
        run: pnpm run build:electron
      
      - name: Build Windows installer
        run: pnpm run electron:dist:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: List build artifacts
        shell: bash
        run: |
          echo "=== Build artifacts in dist-electron ==="
          ls -lh dist-electron/
      
      - name: Upload installer artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-installer
          path: |
            Financials Automation/dist-electron/*.exe
            Financials Automation/dist-electron/*.yml
          retention-days: 30
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Financials Automation/dist-electron/*.exe
          body: |
            ## Financial Statement Generator - Windows Installer
            
            ### Installation Files:
            - **Setup Installer**: `Financial Statement Generator-Setup-*.exe` - Full installer with NSIS
            - **Portable Version**: `Financial Statement Generator-*-Portable.exe` - No installation required
            
            ### System Requirements:
            - Windows 10 (version 1909+) or Windows 11
            - 64-bit architecture (x64)
            - 4GB RAM minimum (8GB recommended)
            - 500MB disk space
            
            ### Installation Instructions:
            1. Download the appropriate installer file
            2. Run the installer with Administrator privileges
            3. Follow the setup wizard
            4. Configure database connection on first launch
            
            For detailed instructions, see [EXE Instructions.md](https://github.com/${{ github.repository }}/blob/main/Financials%20Automation/EXE%20Instructions.md)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
