name: Copilot Network Configuration

on:
  workflow_dispatch:
  push:
    branches: [ main, Schedule-III-Drafting-Automation ]
  pull_request:
    branches: [ main ]

jobs:
  setup-network:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for all branches
          
      - name: Setup network connectivity
        run: |
          echo "Configuring network access for GitHub Copilot..."
          # Test connectivity to required endpoints
          echo "Testing connectivity to github.com..."
          ping -c 3 github.com || echo "github.com unreachable"
          
          echo "Testing connectivity to api.githubcopilot.com..."
          ping -c 3 api.githubcopilot.com || echo "api.githubcopilot.com unreachable"
          
          # Configure DNS if needed
          echo "Current DNS configuration:"
          cat /etc/resolv.conf
          
      - name: Verify Git configuration
        run: |
          echo "Current Git configuration:"
          git config --list
          
          echo "Available branches:"
          git branch -a
          
          echo "Verifying branch existence:"
          git show-ref --verify --quiet refs/heads/Schedule-III-Drafting-Automation || \
          git checkout -b Schedule-III-Drafting-Automation origin/Schedule-III-Drafting-Automation
          
      - name: Test Git operations
        run: |
          echo "Testing Git operations..."
          git fetch origin
          git status
          
          # Test git diff with proper syntax
          echo "Testing git diff..."
          git diff HEAD~1 HEAD -- . || echo "No differences found"