name: Windows Electron Build

on:
  workflow_dispatch:
  push:
    branches:
      - Schedule-III-Drafting-Automation

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
                
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
                
      - name: Install pnpm
        run: npm install -g pnpm
        working-directory: Financials Automation

      - name: Create .env file
        run: |
          echo "NODE_ENV=production" > .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> .env
          echo "APP_NAME=Financial Statement Generator" >> .env
          echo "LOG_LEVEL=info" >> .env
          echo "DB_CONNECTION_POOL_MIN=2" >> .env
          echo "DB_CONNECTION_POOL_MAX=10" >> .env
          echo "SESSION_TIMEOUT_MINUTES=1440" >> .env
          echo "MAX_FILE_SIZE_MB=50" >> .env
          echo "ENABLE_AUTO_BACKUP=true" >> .env
          echo "BACKUP_RETENTION_DAYS=30" >> .env
        working-directory: Financials Automation
        
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        working-directory: Financials Automation

      - name: Generate Prisma client
        run: pnpm exec prisma generate
        working-directory: Financials Automation

      - name: Build web application
        run: pnpm run build
        working-directory: Financials Automation

      - name: Compile Electron scripts
        run: pnpm run build:electron
        working-directory: Financials Automation

      - name: Build Windows installer
        run: npx electron-builder --win --config electron-builder.config.cjs
        working-directory: Financials Automation

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: Financial-Statement-Generator-Installer
          path: Financials Automation/dist-electron/*.exe
        
